spring.application.name=sigat
spring.datasource.url=${{MySQL.MYSQL_URL}}
spring.jpa.hibernate.ddl-auto=none
spring.datasource.username=${{MySQL.MYSQLPASSWORD}}
spring.datasource.password=${{MySQL.MYSQLUSER}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver