spring.application.name=sigat
spring.datasource.url=jdbc:mysql://localhost:3306/sigat
spring.jpa.hibernate.ddl-auto=none
spring.datasource.username=sigat
spring.datasource.password=sigat
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver